/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

int *
fact_1_svc(number *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("fact(%d) is called\n", argp->a);
	int n = argp->a;
	int res = 1;
	for (int i = 1; i <= n; i++){
		res = res * i;
	}
	result = res;

	return &result;
}
