/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "grt.h"

int *
grt_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("greatest(%d, %d, %d) is called", argp->a, argp->b, argp->c);
	int x, y, z, max;
	x = argp->a;
	y = argp->b;
	z = argp->c;
	max = -999;
	if (x > max) max = x;
	if (y > max) max = y;
	if (z > max) max = z;
	result = max;

	return &result;
}
