/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "grt.h"


void
grt_prog_1(char *host, int x, int y, int z)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  grt_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GRT_PROG, GRT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	grt_1_arg.a = x;
	grt_1_arg.b = y;
	grt_1_arg.c = z;
	result_1 = grt_1(&grt_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("result = %d\n" , *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	grt_prog_1 (host, atoi(argv[2]), atoi(argv[3]), atoi(argv[4]));
exit (0);
}
