/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sod.h"

int *
sod_1_svc(number *argp, struct svc_req *rqstp)
{
	int SumOfDigits(int a){
		int sum = 0;
		while(a > 0){
			sum += a % 10;
			a /= 10;
		}
		return sum;
	}
	
	static int  result;

	printf("SumOfDigits(%d) is called", argp->a);
	result = SumOfDigits(argp->a);

	return &result;
}
